### ISSUE TITLE
Checklist for hardfork of Mirana

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#3]
- [x] Rename Lina/Aggron to Mirana/Pudge
  - [x] Deprecate `/aggron` pathname and redirect to `/pudge` pathname
  - [x] Rename labels of links to mainnet/testnet at the top right corner
- [x] Update UI and an easter egg for the hardfork: discuss with nervape
- [x] Countdown of hardfork and notification with a link to https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0037-ckb2021/0037-ckb2021.md#ckb2021-timeline
- [x] Synchronize with cells of `data1` script: https://explorer.nervos.org/aggron/transaction/0x5187ad53f4396bfbb2276b7398032650dfdba1043f6b6a684e2d46d7647e1366
- [x] Support new format of addresses
    - short address https://explorer.nervos.org/aggron/address/ckt1qyqw975zuu9svtyxgjuq44lv7mspte0n2tmqa703cd
    - new long address https://explorer.nervos.org/aggron/address/ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0zl2pwwzcx9jryfwq26lk0dcq4uhe49as2gh56a

**Comment by Keith-CY** [comment]
## Color Schema
Figma: https://www.figma.com/file/vcUXOw8tiivtsk14189xda/ckb-explorer-copy?node-id=0%3A1
Rules: 
```
画布的最左侧哈，这一块是
表格那部分好像当初是程序自己做的，所以我们没有设计稿，我们这面暂时出的方案是，所有表格里的颜色把三个主要的颜色替换掉，其他的暂时保留，具体替换的颜色写在 figma 里面啦
然后主网页面以前的绿色字体现在全部替换成 #00CC9B 
测试网的原本蓝色的字体全部替换成 #9A2CEC
首页上面的图标从渐变颜色替换成了纯色，分别是 Nervos 现在主色的两个灰 #232323 #484E4E
颜色上差不多就这些，首页的排版我们也稍微改了一下，为了后面加彩蛋的 banner，你先看看呀，有啥问题或是有啥需要修改的
```

There might be some conflicts between figma and rules, we could follow the rules and feedback the design team about these conflicts to make it clear.

**Comment by yanguoyu** [comment]
There are [two kinds of blue](https://github.com/nervosnetwork/ckb-explorer-frontend/blob/2082e88f52c381f3d4a99ff3008463a2be0dda87/src/constants/common.ts#L11-L14) for the test network. But there is only one kind of green for the main network. Are the two blue colors of the test network replaced with `#9a2cec`?
***
Which one is means the icon on the home page refers?
1. https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/assets/ckb_logo.png This picture has no color.Only header has background color.
2. <img width="1439" alt="image" src="https://user-images.githubusercontent.com/12881040/163300615-1be29fe0-e61d-4794-bc28-04f7f63ffb35.png">

**Comment by Keith-CY** [comment]
> There are [two kinds of blue](https://github.com/nervosnetwork/ckb-explorer-frontend/blob/2082e88f52c381f3d4a99ff3008463a2be0dda87/src/constants/common.ts#L11-L14) for the test network. But there is only one kind of green for the main network. Are the two blue colors of the test network replaced with `#9a2cec`?
> 
> Which one is means the icon on the home page refers?
> 
> 1. [https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/assets/ckb_logo.png](https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/assets/ckb_logo.png?rgh-link-date=2022-04-14T02%3A22%3A58Z) This picture has no color.Only header has background color.
> 2. <img alt="image" width="1439" src="https://user-images.githubusercontent.com/12881040/163300615-1be29fe0-e61d-4794-bc28-04f7f63ffb35.png">

The `secondary` theme is used in https://github.com/nervosnetwork/ckb-explorer-frontend/blob/2082e88f52/src/components/Header/BlockchainComp/styled.tsx#L23 and https://github.com/nervosnetwork/ckb-explorer-frontend/blob/2082e88f52/src/components/Header/LanguageComp/styled.tsx#L7

![image](https://user-images.githubusercontent.com/7271329/163427970-d77084d2-95d5-4a18-9a07-4eca24648603.png)

![image](https://user-images.githubusercontent.com/7271329/163427706-6df36047-a430-438d-bd6c-ab45f7ef9662.png)

I think it's ok to use the same color as the primary one

**Comment by Keith-CY** [comment]
> There are [two kinds of blue](https://github.com/nervosnetwork/ckb-explorer-frontend/blob/2082e88f52c381f3d4a99ff3008463a2be0dda87/src/constants/common.ts#L11-L14) for the test network. But there is only one kind of green for the main network. Are the two blue colors of the test network replaced with `#9a2cec`?
> 
> Which one is means the icon on the home page refers?
> 
> 1. [https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/assets/ckb_logo.png](https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/assets/ckb_logo.png?rgh-link-date=2022-04-14T02%3A22%3A58Z) This picture has no color.Only header has background color.
> 2. <img alt="image" width="1439" src="https://user-images.githubusercontent.com/12881040/163300615-1be29fe0-e61d-4794-bc28-04f7f63ffb35.png">

Actually they don't mean icons but diagrams

![image](https://user-images.githubusercontent.com/7271329/163428587-2370542d-245b-42d8-b23f-f248ae249218.png)
Left one use pure color `#232323`
Right one use pure color `#484e4e`

**Comment by Keith-CY** [comment]
New color schema should be activated on hardfork and the countdown algorithm is mentioned in https://discord.com/channels/870891180035031071/871645196083937300/964768808311087104

**Comment by yanguoyu** [comment]
New Color schema link https://www.figma.com/file/vcUXOw8tiivtsk14189xda/ckb-explorer-copy?node-id=548%3A75581

**Comment by yanguoyu** [comment]
Fima change some layout, should i finish the layout changes?
1. Chart location has changed
Before:
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/12881040/164201869-340f210a-9ff3-4e40-9167-42f379e8147c.png">
After:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/12881040/164201955-abff31d1-4e63-4c11-a879-8e3fb84fa31b.png">
2. Changed from two columns to one column
Before: `Latest Blocks` block is align with `Latest Transactions` block
After: `Latest Blocks` block is on the top of`Latest Transactions` block

**Comment by Keith-CY** [comment]
> Fima change some layout, should i finish the layout changes?
> 
> 1. Chart location has changed
>    Before:
> 
> <img alt="image" width="1351" src="https://user-images.githubusercontent.com/12881040/164201869-340f210a-9ff3-4e40-9167-42f379e8147c.png">
> 
> After:
> <img alt="image" width="552" src="https://user-images.githubusercontent.com/12881040/164201955-abff31d1-4e63-4c11-a879-8e3fb84fa31b.png">
> 
> 2. Changed from two columns to one column Before: `Latest Blocks` block is align with `Latest Transactions` block After: `Latest Blocks` block is on the top of`Latest Transactions` block

I've confirmed that there're some changes in layout and should be updated.

1. Layout in the diagram you mentioned above
2. Layout in list item of blocks and transactions for mobile view, from single column to two columns
3. Layout of media in the footer, discord should be added

**Comment by yanguoyu** [comment]
The charts at main page data will also be changed to `Hash Rate` and `Difficulty`?(original is `Average Block Times` and `Hash Rate`)
<img width="522" alt="image" src="https://user-images.githubusercontent.com/12881040/164619806-2668bbb6-b3a2-49fe-8406-2817d648f80f.png">

**Comment by Keith-CY** [comment]
> The charts at main page data will also be changed to `Hash Rate` and `Difficulty`?(original is `Average Block Times` and `Hash Rate`) <img alt="image" width="522" src="https://user-images.githubusercontent.com/12881040/164619806-2668bbb6-b3a2-49fe-8406-2817d648f80f.png">

They're just placeholders and functionalities should not be changed.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/ckb-explorer-frontend/pull/925

**Comment by yanguoyu** [comment]
easter egg design: https://www.figma.com/file/vcUXOw8tiivtsk14189xda/ckb-explorer-copy?node-id=549%3A43039

**Comment by Keith-CY** [comment]
Update new banner

Slogan: 
https://codepen.io/giana/pen/qmKNeE
![image](https://user-images.githubusercontent.com/7271329/167542866-0bfaebc5-5f1b-436f-8c0e-f6c04a0e0d7c.png)

Banner:
![image](https://user-images.githubusercontent.com/7271329/167542918-792b90a9-8444-43c2-ae2c-d0740497390b.png)
