### ISSUE TITLE
RGB++ support v1.3

### ISSUE THREAD

**Issue by poor-defined** [Magickbase/ckb-explorer-public-issues#644]
To improve the UX of RGB++, a proposal about some enhance and fix is made here.

- PRD： https://vs0cjf.axshare.com/?id=q205n4&p=support_rgb___v1_3&g=1&sc=3

- [x] Add RGB++ Attribution for a RGB++ transaction. #656 
- [ ] Update the judge logic of the L1->L2 indicator. #645 
- [ ] Update the Status of RGB++ Cell. #657 
- [x] Update the RGB++ tab of address detail page. #658 
- [ ] Update the tooltip on transaction list on address detail page. #659 
- [x] Update cell status of BTC address detail asset RGB++ Tab #667

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=35067%3A23035&mode=design&t=zsGz3ALW01xi3Gr6-1
<img width="1051" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/6c4b448d-696f-464f-a20d-ae6de7c8b02e">

**Comment by rabbitz** [comment]
update bitcoin vout binding status: https://github.com/nervosnetwork/ckb-explorer/pull/2104
