### ISSUE TITLE
Data Statistics

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/ckb-explorer-public-issues#699]
PRD：https://u7vn34.axshare.com/

**Comment by Kirl70** [comment]
Design Draft(13-1--13-5):
https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=39644-61556&t=9CXwBUQI9Lvs1toq-1
<img width="1036" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/117cdb0e-bbad-421d-bf52-96df158e0f65">

**Comment by rabbitz** [comment]
- [ ] [Data statistics transaction tracking](https://github.com/Magickbase/ckb-explorer-public-issues/issues/723)
- [ ] [Data statistics hot contracts](https://github.com/Magickbase/ckb-explorer-public-issues/issues/724)
- [ ] [Data statistics top senders and receivers](https://github.com/Magickbase/ckb-explorer-public-issues/issues/725)

**Comment by rabbitz** [comment]
1. ckb transaction tracking

```ruby
# 接口
https://blockchain-stats-staging.magickbase.com/api/v1/transaction_tracking

# 参数
duration: 枚举值可选类型为 day week month year all, 不带参数默认值为 all
```

* 统计方式
  * 确定起始时间: 从创世区块的时间戳（blocktimestamp）或数据库记录的最后一条时间戳作为 start_timestamp，然后将 start_timestamp 加 1 小时并取整作为 end_timestamp 进行统计
  * 获取交易IDs：在统计时间范围内，获取所有交易ID (transaction_ids)，并将其切分为每组100条的请求，每组请求结果计算为 [{ transactionId: outputCapacities - inputCapacities }...], 请求完则合并 transactionId 对应计算值
  * 计算交易总数和交易量：
    * 获取到的 transactionId 数量即为1小时内的交易总数
    * 将 outputCapacities - inputCapacities 的结果累加，即为1小时内的交易量
    
2. hot contracts
```ruby
# 接口
https://blockchain-stats-staging.magickbase.com/api/v1/hot_contracts
```

* 统计方式
  * 取 udts 数据，按照 h24_ckb_transactions_count 降序取前 10 条数据
  
3. top senders

```ruby
# 接口
https://blockchain-stats-staging.magickbase.com/api/v1/top_senders
```

* 统计方式
  * 确定时间范围：
    * 获取当前时间的整点数，例如 10:36 则取 10:00
    * 往前推24小时，将时间范围内的数据按1小时间隔进行切片
  * 数据获取和存储
    * 每1小时时间间隔内的数据按照地址 addressId 统计 inputCapacities 和 outputCapacities，并分别存入 Redis
    * 对应的 addressId 的 inputCapacities 和 outputCapacities 进行累加
  * 计算得分并排序
    * 将 inputCapacities - outputCapacities 的值作为 score，addressId 作为 key，放入 Redis 中进行排序
  * 获取前十名
    * 取 score 不为 0 的前10个值作为 topSenders
    * 取 score 不为 0 的倒序前10个值作为 topReceivers
    
4. top receivers

```ruby
# 接口
https://blockchain-stats-staging.magickbase.com/api/v1/top_receivers
```

**Comment by rabbitz** [comment]
5. token analyzer

* 数据查询及统计范围: 类型为 sudt, xudt, 和 xudt_compatible 的已发布 udt，统计当前日期近一年的数据
* 统计方式
    * 更新时间: 每天 UTC 0 点统计前一天的数据。
    * 交易图表
      * 获取当前时间对应的 UTC 0 点作为结束时间，并将前一天的 UTC 0 点作为开始时间。
      * 针对 udt 进行交易统计，计算对应的交易数 (transactions_count)。
      * 统计 inputUdtAmounts 和 outputUdtAmounts，并计算 outputUdtAmounts - inputUdtAmounts 作为 transactions_udt_amount
    * 持有人图表
      * 获取当前时间对应的 UTC 0 点作为结束时间，筛选结束时间之前与 udt type_hash 和 cell_type 一致的活跃 cell_outputs
      * 按地址 (addressId) 累加对应的 udtAmount，地址总数即为 holdersCount。
    * Top 持有人图表
      * 获取当前时间对应的 UTC 0 点作为结束时间，筛选结束时间之前与 udt type_hash 和 cell_type 一致的活跃 cell_outputs，累加 udtAmount 作为 totalUdtAmount。
      * 分别取出 udtAmount 排名前 100，50，20，10 的地址，并计算其百分比

  5.1 search udt

  ```ruby
  # 接口
  https://blockchain-stats-staging.magickbase.com/api/v1/udts/search

  # 参数
  q: string 类型
  ```

  * 对 full_name 和 symbol 进行模糊匹配, 或者 type_hash 进行完全匹配

  5.2 udt indicators

  ```ruby
  # 接口
  https://blockchain-stats-staging.magickbase.com/api/v1/udts/:type_hash/indicators
  ```

**Comment by rabbitz** [comment]
6. top holders
```ruby
# 接口
https://blockchain-stats-staging.magickbase.com/api/v1/top_holders
```

* 统计方式
  * 更新时间: 整点小时
  * 确定时间范围: 当前时间整点小时近 24 小时

**Comment by Keith-CY** [comment]
This issue is past its expected completion date (2025-07-28). 
- Expected done date: Not set
- Iteration end date: 2025-07-28

Please either:
1. Move it out of the current iteration if it's no longer a priority
2. Update the expected completion date if it's still important
3. Take immediate action to complete it

@Magickbase/pm Please review and decide on the next steps.
